baseURL = "warren.co.jp"
languageCode = "jp"
title = "Warren Inc."
themesDir = "../.."
theme = "hugo-serif-theme"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "UA-154590024-1"
  google_tag_manager_id = "GTM-TXK87HW"

  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "Warren Inc - 利益の伴う成長を支援するコンサルティング会社"

  [params.homepage_meta_tags]
    meta_description = "Warren(ウォーレン)は利益の伴う成長を支援するコンサルティング会社です。"
    meta_og_title = "Warren Inc."
    meta_og_type = "website"
    meta_og_url = "https://warren.co.jp"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Warren(ウォーレン)は利益の伴う成長を支援するコンサルティング会社です。"
    meta_twitter_card = "summary"
    meta_twitter_site = "@kkk"
    meta_twitter_creator = "@kkk"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Contents"
    url = "/contents/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
